name: docs

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOCS_CONTEXT: GitHub

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Build VuePress site
        env:
          DOCS_CONTEXT: GitHub
        run: |
          npm ci
          npm install shx
          npm run build
          npm run docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
