name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: flow-connect-dist
          path: flow-connect/dist
  Docs:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.x

      - name: Download dist artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: flow-connect-dist
          path: flow-connect/dist

      - name: Build VuePress site
        env:
          DOCS_CONTEXT: GitHub
        run: |
          npm ci
          npm run docs:build
  Cleanup:
    needs: [Docs]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete dist artifacts
        uses: geekyeggo/delete-artifact@v6.0.0
        with:
          name: flow-connect-dist
          failOnError: false
